application:
  bindAddress: :8446
  production : false
  debug      : false
database:
  address : collector-db:3306
  name    : collector
  username: admin
  password: admin
authentication:
  authority   : https://algotiqa:8443/auth/realms/algotiqa
  clientId    : algotiqa-backend
  clientSecret: PUT_YOUR_KEY_HERE
platform:
  system: https://algotiqa:8449/api/system
messaging:
  address : rabbitmq:5672
  username: admin
  password: admin
  journal:
    directory      : journal
    queueSize      : 1000
    compactMessages: 1000
    dbSpoolInterval: 2
datastore:
  address : collector-data:5432
  name    : datastore
  username: admin
  password: admin
  staging : staging
