application:
  bindAddress: :8446
  production: false
  debug: false
database:
  address: localhost:3402
  name: collector
  username: bitfever
  password: bitfever
authentication:
  authority: https://bitfever-server:8443/auth/realms/bitfever
  clientId: bitfever-backend
  clientSecret: xyz
platform:
  system: https://bitfever-server:8449/api/system
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
datastore:
  address: localhost:3410
  name: datastore
  username: bitfever
  password: bitfever
  staging:  staging
